on:
  push:
  pull_request:

name: Test update download urls
jobs:
  update-downloads:
    name: Update download urls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install -r .github/update_tools/requirements.txt

      - name: Cache local-chromium
        uses: actions/cache@v4
        with:
          path: /home/runner/.local/share/pyppeteer/local-chromium
          key: local-chromium

      - name: run update script
        run: |
          python .github/update_tools/update_downloads.py
