on:
  schedule:
    - cron: "40 17 * * 1" # At 07:00 on each Monday.
    # - cron: "0 7 * * 1" # At 07:00 on each Monday.

name: Update download urls
jobs:
  update-downloads:
    name: Update download urls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install -r .github/update_tools/requirements.txt
      - name: Make update PR
        uses: technote-space/create-pr-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXECUTE_COMMANDS: |
            python .github/update_tools/update_downloads.py
          COMMIT_MESSAGE: "chore: update download urls"
          PR_BRANCH_NAME: "chore-download-url-update"
          PR_TITLE: "chore: update download urls"
